.TH BGROOT 1 "June 2026" "A/UX Workstation" "Local Commands"
.SH NAME
bgroot \- set the root window background from an XPM image
.SH SYNOPSIS
.B bgroot
.I file.xpm
.SH DESCRIPTION
Loads an XPM and sets it as the X root window background.  The fvwm
Appearance menu uses it for the wallpaper collection in
.IR /usr/local/bgs .
.SH SEE ALSO
auxsaver(1), aux(7)
