.TH DIALC-X 1 "June 2026" "A/UX Workstation" "Local Commands"
.SH NAME
dialc-x \- launch dialc in a themed rxvt (fvwm menu entry)
.SH DESCRIPTION
Opens dialc(1) in a synthwave rxvt with the right TERMINFO, font, and
geometry.  This is what the "dialtone" entry on the fvwm Main menu
runs.
.SH SEE ALSO
dialc(1), rxvt(1)
