#!/bin/sh
# fvwm launcher: auxtop in a synthwave xterm
DISPLAY=${DISPLAY:-:0}; export DISPLAY
exec /usr/local/bin/xterm -geometry 100x34 -fn 7x13 \
  -fg 'rgb:7a/f0/ff' -bg 'rgb:19/0a/2e' -cr 'rgb:ff/2a/8a' \
  -title auxtop \
  -e /bin/sh -c 'TERMINFO=/usr/local/ncurses-5.7/share/terminfo; export TERMINFO; exec /usr/local/bin/auxtop'
