#!/bin/sh
# fvwm launcher: dialc (Dialtone AOL client) in a synthwave rxvt
DISPLAY=${DISPLAY:-:0}; export DISPLAY
exec /usr/local/bin/rxvt +sb -geometry 88x28 -fn profont15 -sl 512 \
  -fg 'rgb:7a/f0/ff' -bg 'rgb:19/0a/2e' -cr 'rgb:ff/2a/8a' \
  -title dialtone \
  -e /bin/sh -c 'TERMINFO=/usr/local/ncurses-5.7/share/terminfo; export TERMINFO; exec /usr/local/bin/dialc'
